# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
server: true # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

name: 云淡天高
description: 天高任鸟飞
url: http://riwcwt.github.io


comments :
  provider : custom
